import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //english
        'en_US': {
          'app_name': 'Denis Kebap',
          'phone_number': 'Phone Number',
          'login_with_phone_and_pin': 'Login With Phone & Pin',
          'login_with_phone': 'Login With Phone',

          'enter_your_pin': 'Enter your Pin',
          'login': 'Login',
          'or': 'OR',
          'sign_in_with': 'Sign in with',
          'new_customer': 'New Customer',
          'register_here': 'Register here',
          'existing_customer': 'Existing Customer',
          'create_reset_your_login_pin': 'Create/Reset your Login Pin.',
          'enter_phone_number': 'Enter Phone Number',
          'next': 'Next',
          'otp_verification': 'OTP Verification',
          'please_enter_the_otp': 'Please enter the otp',
          'mobile_number': 'Mobile number',
          'submit_otp': 'Submit OTP',
          'resend_otp': 'Resend OTP',
          'valid_for_minutes': 'Valid for 10 minutes',
          'setup_new_pin': 'Setup New Pin',
          'setup_new_pin_instructions':
              'To set up your PIN create 4 digit code then confirm it below',
          'pin_code': 'Pin Code',
          'confirm_your_pin_code': 'Confirm Your Pin Code',
          'save': 'Save',
          'ok': 'Ok',
          'message_pin_created': 'Your Pin was created successfully',
          'home': 'Home',
          'search': 'Search',
          'cart': 'Cart',
          'account': 'Account',
          'my_account': 'My Account',
          'add': 'Add',
          'ingredients': 'Ingredients',
          'add_ons': 'Add Ons',
          'item_total': 'Item total',
          'net_price': 'Net price',
          'add_item': 'Add Item',
          'recent_search': 'Recent Search',
          "kebab": "Kebap ",
          "kebab_small": "Kebap Small",
          "veggie_kebab": "Veggie Kebap ",
          "select_your_pickup_time": "Select your Pickup Time",
          "bills_details": "Bill Details",
          "past_orders": "PAST ORDERS",
          "edit_account": "Edit Account",
          "name": "Name",
          "email": "Email",
          "current_password": "Current Password",
          "card_details": "Card Details",
          "card_number": "Card Number",
          "valid_until": "Valid until",
          "cvv": "CVV",
          "card_holder": "Card Holder",
          'set_pick_up_time': 'Set Pick up TIme',
          "message_enter_phone_number": "Enter phone number",
          "message_enter_valid_phone_number": "Enter Valid phone number",
          "in": "in",
          "message_enter_pin": "Please enter pin",
          "message_enter_confirm_pin": "Please enter confirm pin",
          "message_pin_does_not_matched": "Pin doesn't matched.",
          "alert": "Alert",
          "message_enter_phone": "Please enter phone number.",
          'error': 'Error',
          'skip': 'Skip',
          'message_password_helper':
              'Password must contain least one(uppercase,lowercase,digit,special character,) and minimum 8 characters',
          'what_are_you_craving_for': 'What are you Craving for?',
          'empty_cart': 'Empty Cart',
          "order_history": "Order History",
          "cancel_order": "Cancel Order",
          "reorder": "Reorder",
          "active_order": "Active Order",
          "past_order": "Past Order",
          "update": "Update",
          "verify": "Verify",
          "delete_account": "Delete Account",
          "cancel": "Cancel",
          "take_a_photo": "Take a Photo",
          "choose_from_gallery": "Choose from gallery",
          'your_customisation': 'Your Customisation',
          'add_new_customisation': 'Add new customisation',
          'continue': 'Continue',
          'confirm': 'Confirm',
          'shopping_cart': 'Shopping Cart',
          'tax_and_charges': 'Tax and charges',
          'vat': 'VAT',
          'total_pay': 'Total Pay',
          'my_pickup_time': 'My Pickup Time',
          'select_pickup_time': 'Select Pickup Time',
          'send_otp': 'Send OTP',
          'term_of_service': 'Term of service',
          'privacy_policy': 'Privacy Policy',
          'terms_and_privacy': 'Terms of service & Privacy Policy',
          'message_empty_cart': 'Your Bag is empty',
          'order': 'Order',
          'check_out_what_is_trending': 'Check out what is trending',
          'start_adding': 'Start Adding',
          'good_morning': 'Good Morning',
          'good_afternoon': 'Good Afternoon',
          'good_evening': 'Good Evening',
          'hint_your_name': 'Your name',
          'hint_your_email': 'Your email',
          'message_enter_name': 'Please enter your name',
          'message_enter_email': 'Please enter your email',
          'message_enter_value': 'Please enter value',
          'message_invalid_email': 'Please enter a valid email address',
          'message_please_select_time_slot': 'Please select time slot.',
          'pickup_time': 'Pickup Time',
          'congratulations': 'Congratulations!',
          'order_placed': 'Order placed!',
          'order_placed_description':
              'You can pick your order from the restaurant on your selected pickup time',
          'disclaimer_title': 'Fine print…',
          'disclaimer_description':
              'Since our dishes are freshly prepared, there may be time deviations depending on the volume of orders - we ask you to take this into account.If we are unable to provide the service due to force majeure, we are released from our obligation to perform for the duration of the restriction.We reserve the right to refuse performance in individual cases.',
          'your_order_has_been_placed': 'Your Order has been Placed',
          'message_shop_closed': 'Sorry we are closed now.',
          'message_no_ingredients_available': 'No Ingredients Available.',
          'message_no_addons_available': 'No AddOns Available.',
          'message_order_time_missing':
              "Some order 's pickup time is missing, So that they are not showing in the orders list. Please go to store in case you face any issue",
          'you_have_no_item_at_this_moment':
              'You have no item at this\nmoment.',
          'empty_list': 'Empty List',
          'preparing': 'Preparing',
          'proceed': 'Proceed',
          'dismiss': "Dismiss",
          'message_confirm_cancel_order':
              "Are you sure you want to cancel this order?",
          'logout': "Logout",
          'message_logout': "Are you sure you want to logout?",
          'user': "User",
          'delete': "Delete",
          'message_delete_account':
              "This will delete your account permanently.You are not able to restore it once deleted.\nAre you sure you want to delete this account?",
          'delayed': 'Delayed',
          'in_queue': 'In Progress',
          'completed': 'Completed',
          'cancelled': 'Cancelled',
          'ready': 'Ready',
          'change_language': 'Change Language',
          'pick_up_in': 'Pick up in',
          'total_price': 'Total Price',
          'order_date': 'Order Date',
          'order_detail': 'Order Detail',
          'message_cancel_order': 'Are you sure you want to... cancel...?',
          'yes': 'Yes',
          'no': 'No',
          'my_orders': 'My Orders',
          'success': 'Success',
          'message_pre_order_confirmation':
              'Are you sure you want to confirm this order?',
          'orders':'Orders',
          'ready_for_pickup': 'Ready to pick-up',
          'confirm_order': 'Confirm order?',
          'message_server_error': 'Server Error',
          'new_user': 'New user',
          'message_phone_already_exists': 'This phone number is already associated with another account!',
          'allow_permissions': 'Allow Permission',
          'go_to_settings': 'Open app settings to allow permission',
          'open_settings': 'Open Settings',
          'payment': 'Payment',
          'message_want_to_add_tip': 'Would you like to add a tip to your payment?',
          'confirmation':'Confirmation',
          'add_tip':'Add Tip',
          'amount':'Amount',
          'invoice':'Invoice',
          'tip':'Tip',
          'open':'Open',
          'download_complete':'Download Complete',
          'file_downloaded_successfully':'File downloaded successfully',
          'cant_able_to_open_file':'Can\'t able to open file',
          'other':'Other',
          'no_tip':'No ',
          'enter_tip_amount':'Enter the tip amount',
          'total_amount_to_pay':'Total amount to pay',
          'continue_with_online_payment':'Continue with online payment',

          'thank_you_for_the_tip':'Thank you for the tip!',
          'download':'Download',
          'continue_as_guest':'Continue as Guest',
          'login_register':'Log in/Register',
          'login_first_cart':'Please log in or register before adding items to your cart.',
          'login_first_orders':'Please log in or register to view orders.',
          'login_first_carts':'Please log in or register to view cart.',


        },

//german

        'de_AT': {
          'app_name': 'Denis Kebap',
          'phone_number': 'Telefonnummer',
          'login_with_phone_and_pin': 'Mit Nummer und Pin anmelden',
          'login_with_phone': 'Mit Telefonnummer anmelden',
          'enter_your_pin': 'Gib deinen Pin ein',
          'login': 'Anmelden',
          'or': 'ODER',
          'sign_in_with': 'Anmelden mit',
          'new_customer': 'Neuer Kunde',
          'register_here': 'Hier registrieren',
          'existing_customer': 'Bestehender Kunde',
          'create_reset_your_login_pin': 'Login Pin erstellen/zurücksetzen',
          'enter_phone_number': 'Telefonnummer eingeben',
          'next': 'Weiter',
          'otp_verification': 'Telefonnummerverifizierung',
          'please_enter_the_otp': 'Bitte gib den Code ein',
          'mobile_number': 'Telefonnummer',
          'submit_otp': 'Code bestätigen',
          'resend_otp': 'Code erneut senden',
          'valid_for_minutes': 'Gültig für 10 Minuten',
          'setup_new_pin': 'Neue Pin erstellen',
          'setup_new_pin_instructions':
              'Erstelle einen vierstelligen Code und klicke auf Bestätigen',
          'pin_code': 'Pin Code',
          'confirm_your_pin_code': 'Bestätigen',
          'save': 'Speichern',
          'ok': 'Okay',
          'message_pin_created': 'Deine Pin wurde erfolgreich erstellt',
          'home': 'Home',
          'search': 'Suchen',
          'cart': 'Einkaufswagerl',
          'account': 'Konto',
          'my_account': 'Mein Konto',
          'add': 'Hinzufügen',
// 'add': '+',
          'ingredients': 'Zutaten',
          'add_ons': 'Zusätzlich',
          'item_total': 'Artikelpreis',
          'net_price': 'Nettopreis',
          'add_item': 'Artikel hinzufügen',
          'recent_search': 'letzte Suche',
          "kebab": "Kebap",
          "kebab_small": "Kebap klein",
          "veggie_kebab": "Veggie Kebap",
          "select_your_pickup_time": "Wähle die Abholzeit aus",
          "bills_details": "Rechnungsdetails",
          "past_orders": "Deine letzten Bestellungen",
          "edit_account": "Konto bearbeiten",
          "name": "Name",
          "email": "Email",
          "current_password": "Aktuelles Passwort",
          "card_details": "Kreditkartenangaben",
          "card_number": "Kartennummer",
          "valid_until": "Gültig bis",
          "cvv": "CVV",
          "card_holder": "Karteninhaber",
          'set_pick_up_time': 'Wähle die Abholzeit aus',
          "message_enter_phone_number": "Telefonnummer eingeben",
          "message_enter_valid_phone_number":
              "Eine gültige Telefonnummer eingeben",
          "in": "in",
          "message_enter_pin": "Bitte gib deine Pin ein",
          "message_enter_confirm_pin": "Bitte gib deinen verifizierten Pin ein",
          "message_pin_does_not_matched": "Die Pin ist ungültig",
          "alert": "Warnung",
          "message_enter_phone": "Telefonnummer eingeben",
          'error': 'Fehler',
          'message_password_helper':
              'Dein Passwort muss mindestens einen Großbuchstaben, '
                  'einen Kleinbuchstaben, eine Ziffer und ein Sonderzeichen enthalten',
          'what_are_you_craving_for': 'Wonach gelüstet es dich?',
          'empty_cart': 'Leeres Einkaufswagerl',
          "order_history": "Bestellverlauf",
          "cancel_order": "Bestellung stornieren",
          "reorder": "Nochmal bestellen",
          "active_order": "Aktive Bestellung",
          "past_order": "Letzte Bestellung",
          "update": "aktualisieren",
          "verify": "Verifizieren",
          "delete_account": "Konto löschen",
          "cancel": "Abbrechen",
          "take_a_photo": "Ein Foto machen",
          "choose_from_gallery": "Aus Galerie wählen",
          'your_customisation': 'Deine Personalisierung',
          'add_new_customisation': 'Neue Personalisierung',
          'continue': 'Fortsetzen',
          'confirm': 'Bestätigen',
          'shopping_cart': 'Einkaufswagerl',
          'tax_and_charges': 'Steuern und Gebühren',
          'vat': 'MwSt.',
          'total_pay': 'Gesamtpreis',
          'my_pickup_time': 'Meine Abholzeit',
          'select_pickup_time': 'Abholzeit wählen',
          'send_otp': 'E-Mail verifizieren',
          'term_of_service': '',
          'privacy_policy': 'Datenschutzrichtlinien',
          'terms_and_privacy': 'Nutzungsbedingungen und Datenschutzrichtlinie',
          'message_empty_cart': 'Ihr Einkaufswagerl ist leer',
          'order': 'Bestellen',
          'check_out_what_is_trending': 'Was ist trendy',
          'start_adding': 'Hinzufügen',
          'good_morning': 'Guten Morgen',
          'good_afternoon': 'Guten Tag',
          'good_evening': 'Guten Abend',
          'hint_your_name': 'Dein Name',
          'hint_your_email': 'Ihre E-Mail Adresse',
          'message_enter_name': 'Bitte gib deinen Namen ein',
          'message_enter_email': 'Bitte Email eingeben',
          'message_enter_value': 'Bitte Wert eingeben',
          'message_invalid_email': 'Bitte gib eine gültige Email Addresse an',
          'message_please_select_time_slot': 'Bitte wähle deine Abholzeit.',
          'pickup_time': 'Abholzeit',
          'congratulations': 'Herzlichen Glückwunsch!',
          'order_placed': 'Bestellung aufgegeben!',
          'order_placed_description':
              'Sie können Ihre Bestellung zu Ihrer gewählten Abholzeit im Restaurant abholen.',
          'disclaimer_title': 'Kleingedrucktes…',
         // 'disclaimer_description': 'Da unsere Speisen frisch zubereitet werden kann es je nach Bestellaufkommen zu Zeitabweichungen kommen - wir ersuchen dich das zu berücksichtigen.Können wir die Leistung aufgrund höherer Gewalt nicht erbringen, sind wir für die Dauer der Einschränkung von unserer Leistungspflicht befreit.Wir behalten uns das Recht vor, die Leistung im Einzelfall zu verweigern.',
          'disclaimer_description': 'Da unsere Speisen frisch zubereitet werden, kann es je nach Bestellaufkommen zu Zeitabweichungen kommen. Wir ersuchen dich, das zu berücksichtigen. Können wir die Leistung aufgrund höherer Gewalt nicht erbringen, sind wir für die Dauer der Einschränkung von unserer Leistungspflicht befreit. Wir behalten uns das Recht vor, die Leistung im Einzelfall zu verweigern.',


          'your_order_has_been_placed': 'Deine Bestellung wurde aufgenommen.',
          'message_shop_closed': 'Sorry, wir haben gerade geschlossen.',
          'message_no_ingredients_available': 'Keine Zutaten vorhanden',
          'message_no_addons_available': 'Keine AddOns vorhanden',
          'message_order_time_missing':
              "Bei einigen Bestellungen fehlt die Abholzeit, sodass sie nicht in der Bestellliste angezeigt werden. Bitte gehen Sie zum Geschäft, falls Sie auf ein Problem stoßen",
          'you_have_no_item_at_this_moment': 'Du hast gerade keinen Artikel.',
          'empty_list': 'Leer',
          'preparing': 'In Bearbeitung',
          'proceed': 'Fortfahren',
          'dismiss': "Verwerfen",
          'message_confirm_cancel_order':
              "Sind Sie sicher, dass Sie die Bestellung stornieren möchten",
          'logout': "Abmelden",
          'message_logout': "Sind Sie sicher, dass Sie sich abmelden wollen?",
          'user': "Benutzer",
          'delete': "löschen",
          'message_delete_account':
              "Dadurch wird Ihr Konto dauerhaft gelöscht. Sie können es nach dem löschen nicht wiederherstellen.\nSind Sie sicher, dass Sie dieses Konto löschen möchten?",
          'delayed': 'Verspätet',
          'in_que': 'Eingereiht',
          'completed': 'Abgeschlossen',
          'cancelled': 'Storniert',
          'ready': 'Bereit',
          'change_language': 'Sprache ändern',
          'pick_up_in': 'Abholen in ',
          'total_price': 'Gesamtpreis',
          'order_date': 'Bestelldatum',
          'order_detail': 'Bestelldetails',
          'message_cancel_order':
              'Sind Sie sicher, dass Sie die Bestellung stornieren möchten',
          'yes': 'Ja',
          'no': 'Nein',
          'my_orders': 'Meine Bestellungen',
          'success': 'Erfolg',
          'message_pre_order_confirmation':
              'Möchten Sie diese Bestellung wirklich bestätigen?',
          'in_queue': 'In der Warteschlange',
          'orders': 'Bestellungen',
          'ready_for_pickup': 'Abholbereit',
          'confirm_order': 'Bestellung bestätigen?',
          'message_server_error': 'Serverfehler',
          'new_user': 'Neuer Benutzer',
          'message_phone_already_exists': 'Diese Telefonnummer ist bereits mit einem anderen Konto verknüpft!',
          'allow_permissions': 'Permitir permiso',
          'go_to_settings': 'Abra la configuración de la aplicación para permitir el permiso',
          'open_settings': 'Configuración abierta',
          'payment': 'Zahlung',
          'message_want_to_add_tip': 'Möchten Sie Ihrer Zahlung ein Trinkgeld hinzufügen?',
          'confirmation':'Bestätigung',
          'add_tip':'Trinkgeld hinzufügen',
          'amount':'Betrag',
          'invoice':'Rechnung',
          'tip':'Trinkgeld',
          'open':'Öffnen',
          'download_complete':'Download abgeschlossen',
          'file_downloaded_successfully':'Datei erfolgreich heruntergeladen',
          'cant_able_to_open_file':'Datei kann nicht geöffnet werden',
          'other':'Andere',
          'no_tip':'Nein Trinkgeld',
          'enter_tip_amount':'Geben Sie den Trinkgeldbetrag ein',
          'total_amount_to_pay':'Zu zahlender Gesamtbetrag',
          'continue_with_online_payment':'Weiter mit Online-Bezahlung',
          'thank_you_for_the_tip':'Vielen Dank für das Trinkgeld!',
          'download' : 'Herunterladen',
          'continue_as_guest' : 'Vorschau',
          'login_register' : 'Anmelden/Registrieren',
          'login_first_cart' : 'Bitte melden Sie sich an oder registrieren Sie sich, bevor Sie Artikel in Ihren Warenkorb legen.',
          'login_first_orders': 'Bitte melden Sie sich an oder registrieren Sie sich, um Bestellungen anzuzeigen.',
          'login_first_carts': 'Bitte anmelden, um fortfahren zu können.',





        },
      };
}
